# Jekyll Configuration Example for Battle Bots Arsenal

# Site settings
title: Battle Bots Arsenal
description: Check out the battle bots we've designed and built as a team for competitions!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  bots:
    output: true
    permalink: /bots/:path/

# Default front matter settings
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: "bots"
    values:
      layout: bot
  - scope:
      path: "index.md"
    values:
      layout: home
  - scope:
      path: "calculator.md"
    values:
      layout: page

# Navigation
header_pages:
  - index.md
  - calculator.md

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
